// The operating system's canon on this site: one vocabulary, and proof that is real.
//
// lib/generated/vocabulary.ts and lib/generated/specimens.ts are generated by the operating
// system (scripts/export_site_canon.py) from core/vocabulary.py and core/specimens.py. The OS
// side (scripts/check_cross_repo.py) holds those files equal to a fresh export. This side holds
// the site to them: every definition the site states is the canon's, no retired name appears in
// shipped copy, and the proof page shows only real public research or placeholders.

import assert from "node:assert/strict";
import { readdirSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { test, describe } from "node:test";

import {
  canonGroups,
  canonRetired,
  canonStages,
  canonTerm,
  canonTerms,
  retiredDetectors,
  specimenDisclosure,
  specimenList,
  termAnchor,
} from "../lib/canon.ts";
import { terminology } from "../lib/content.ts";
import { llmsTxt } from "../lib/llms.ts";
import { guidePages, indexablePaths } from "../lib/pages.ts";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (rel: string) => readFileSync(path.join(repoRoot, rel), "utf8");
const stripComments = (s: string) => s.replace(/\/\*[\s\S]*?\*\//g, " ").replace(/(^|\s)\/\/[^\n]*/g, " ");

describe("the generated canon", () => {
  test("both files are generated by the operating system and say so", () => {
    for (const rel of ["lib/generated/vocabulary.ts", "lib/generated/specimens.ts"]) {
      const text = read(rel);
      assert.match(text, /^\/\/ GENERATED by the operating system/, `${rel} lost its generated header`);
      assert.match(text, /check_cross_repo\.py fails when this file and a fresh export differ/);
    }
  });

  test("every term is complete, every cross-reference resolves, and no two share an anchor", () => {
    const anchors = new Set<string>();
    for (const t of canonTerms) {
      for (const f of ["label", "definition", "decidedBy", "evidence"] as const) {
        assert.ok(String(t[f]).trim().length > 0, `${t.key}: empty ${f}`);
      }
      for (const n of t.notSameAs) assert.ok(canonTerm(n.key), `${t.key}: unknown term ${n.key}`);
      const a = termAnchor(t.key);
      assert.ok(!anchors.has(a), `duplicate anchor ${a}`);
      anchors.add(a);
    }
    for (const g of canonGroups) for (const k of g.terms) assert.ok(canonTerm(k), `group ${g.key}: ${k}`);
    const grouped = canonGroups.flatMap((g) => g.terms as readonly string[]);
    assert.deepEqual([...grouped].sort(), canonTerms.map((t) => t.key).sort(), "a term sits in no group, or two");
  });

  test("the owner's ten terms are all defined, directly or by what replaced them", () => {
    const current = new Set(canonTerms.map((t) => t.label.toLowerCase()));
    const retired = new Set(canonRetired.map((r) => r.term.toLowerCase()));
    for (const name of ["FIT contractor", "Decision-maker", "Commercial need", "Qualified Conversation",
      "Accepted Sales Opportunity", "Appointment", "Warm Handoff", "Billable opportunity",
      "Agency and contractor responsibility"]) {
      assert.ok(current.has(name.toLowerCase()), `not defined: ${name}`);
    }
    for (const name of ["Qualified Opportunity", "Accepted Opportunity"]) {
      assert.ok(retired.has(name.toLowerCase()), `the retired name ${name} does not say what replaced it`);
    }
  });

  test("the stages a client sees are named, in order, with no internal token", () => {
    assert.ok(canonStages.length >= 10);
    for (const s of canonStages) assert.doesNotMatch(s.label, /_|[A-Z]{4,}/, `${s.stage} shows an internal token`);
    assert.ok(canonStages.some((s) => s.label === "Taken on by you"));
  });

  test("there is no billable opportunity, and the definition says so first", () => {
    assert.match(canonTerm("billable_opportunity").definition, /^There is none\./);
  });
});

describe("one definition per term, on every page that states one", () => {
  test("the terminology /how-it-works and /pricing render is the canon's, word for word", () => {
    for (const t of terminology) {
      const c = canonTerm(t.key.replace(/-/g, "_"));
      assert.equal(t.term, c.label, `${t.key}: label differs from the canon`);
      assert.equal(t.definition, c.definition, `${t.key}: definition differs from the canon`);
    }
  });

  test("/llms.txt states every public definition verbatim", () => {
    const llms = llmsTxt();
    for (const t of canonTerms) assert.ok(llms.includes(`- ${t.label}: ${t.definition}`), `llms.txt lacks ${t.key}`);
  });

  test("/definitions and /sample-deliverables are registered, indexable and render from the canon", () => {
    for (const slug of ["definitions", "sample-deliverables"]) {
      assert.ok(guidePages.some((p) => p.slug === slug), `${slug} is not registered`);
      assert.ok(indexablePaths.includes(`/${slug}`));
    }
    const defs = stripComments(read("app/definitions/page.tsx"));
    assert.match(defs, /termsInGroup\(g\.key\)\.map/, "/definitions no longer renders from the canon");
    assert.match(defs, /"@type": "DefinedTermSet"/);
    const proof = stripComments(read("app/sample-deliverables/page.tsx"));
    assert.match(proof, /specimenList\.map/, "/sample-deliverables no longer renders from the canon");
  });
});

describe("no retired name in shipped copy", () => {
  function walk(dir: string, out: string[] = []): string[] {
    for (const entry of readdirSync(dir)) {
      const full = path.join(dir, entry);
      if (statSync(full).isDirectory()) walk(full, out);
      else if (/\.tsx?$/.test(entry)) out.push(full);
    }
    return out;
  }
  // The generated vocabulary is where retirement is DEFINED, so it is the one file excluded.
  const shipped = [
    ...walk(path.join(repoRoot, "app")),
    ...walk(path.join(repoRoot, "components")),
    ...["content", "qualification", "site", "pages", "llms", "events", "canon"].map((n) => path.join(repoRoot, "lib", `${n}.ts`)),
    path.join(repoRoot, "lib", "generated", "specimens.ts"),
  ].map((f) => ({ rel: path.relative(repoRoot, f), text: stripComments(readFileSync(f, "utf8")) }));
  shipped.push({ rel: "/llms.txt (rendered)", text: llmsTxt() });

  test("the operating system's retired-name detectors find nothing on this site", () => {
    const hits: string[] = [];
    for (const { rel, text } of shipped) {
      for (const d of retiredDetectors()) {
        const m = text.match(d.re);
        if (m) hits.push(`${rel}: [${d.term}] ${JSON.stringify(m[0])}`);
      }
    }
    assert.deepEqual(hits, [], `retired names in shipped copy:\n  ${hits.join("\n  ")}`);
  });

  test("the detectors are live", () => {
    const fired = (s: string) => retiredDetectors().some((d) => d.re.test(s));
    assert.ok(fired("We hand you a qualified opportunity."));
    assert.ok(fired("Each accepted opportunity is counted."));
    // JSX wraps a sentence across source lines; the 2026-09-19 live miss was exactly this shape.
    assert.ok(fired("site visits, qualified\n              opportunities, or any count of them"));
    assert.ok(!fired("The Opportunity Engine hands off an accepted sales opportunity."));
    // SENSE-SCOPED, since 2026-09-20. "Screened interest" carries two meanings: what the $1,500
    // plan was once said to hand over (retired), and the operating system's own five-criterion
    // row verdict (current, internal — core/qcs.py, never client-facing). The generated pattern
    // is written against the retired SENSE only, so these hold that it still discriminates in
    // V8 — a different regex engine from the one core/vocabulary.py was tested against.
    assert.ok(fired("Managed Outbound hands off screened interest every week."));
    assert.ok(fired("You receive screened interest, not a raw list."));
    assert.ok(!fired("Screened interest is the five-criterion verdict run before a handoff."));
  });
});

describe("proof of delivery: real, or a production render with placeholders", () => {
  test("five specimens, each stating what it is and when it is produced", () => {
    assert.deepEqual(specimenList.map((s) => s.key), [
      "target-account-record", "qualification-record", "qualified-conversation-handoff",
      "opportunity-brief", "client-report",
    ]);
    for (const s of specimenList) {
      assert.ok(s.when.length > 10 && s.provenance.length > 40, `${s.key} does not say what it is`);
      assert.ok(canonTerm(s.term), `${s.key} names no defined term`);
    }
    assert.match(specimenDisclosure, /not a client document/);
  });

  test("the real account withholds the firm, the link and the addresses", () => {
    const acct = specimenList.find((s) => s.key === "target-account-record")!.body;
    assert.match(acct, /name withheld/);
    assert.match(acct, /link withheld/);
    assert.doesNotMatch(acct, /https?:\/\//);
  });

  test("no number in a rendered document is a result: every count is a placeholder", () => {
    for (const key of ["qualified-conversation-handoff", "opportunity-brief", "client-report"]) {
      const body = specimenList.find((s) => s.key === key)!.body;
      const stray = body
        .replace(/24 hours/g, "")
        .replace(/^## \d\. /gm, "")
        .replace(/\b[Ss]ection \d\b/g, "")
        .match(/\d/g);
      assert.equal(stray, null, `${key} carries a number that is not a placeholder`);
    }
  });
});
