import type { Metadata } from "next";
import { getLegalRoute, pageMetadata, standalonePageJsonLd } from "@/lib/pages";
import { ANSWER_KEYS, QUESTION_LABELS } from "@/lib/qualification";
import { ATTRIBUTION_KEYS, ATTRIBUTION_LABELS } from "@/lib/attribution";
import { EVENT_LABELS, EVENT_NAMES } from "@/lib/events";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import { brandName, contactEmail, entityFormationState, legalEntity, legalEntityName, privacyLastUpdated } from "@/lib/site";

// WHAT CHANGED ON 2026-09-17: the FACTUAL descriptions of what this site records and what the
// service does — the fit check's new question (generated, as before), the visit-attribution
// fields (generated from lib/attribution.ts, so the list cannot drift from the code), the use
// of session storage, the first-party conversion events (generated from lib/events.ts, same
// discipline), the fields the form no longer asks (role; the fee is optional), and what the
// top plan records from a conversation with a business contact. No rights, retention,
// legal-basis or contact clause was reworded. This policy has still not been reviewed by
// counsel (SETUP.md); that note stands.
//
// WHAT CHANGED ON 2026-09-21: `visit_start` joined the generated event list, and the
// visit-origin paragraph was corrected — it said those values were "not sent anywhere on
// [their] own" and never received without a submission, while every first-party event had
// carried them since 2026-09-17. The crawler filter on /api/event is described. See
// `privacyLastUpdated` in lib/site.ts; /terms did not change and keeps its own date.

const route = getLegalRoute("privacy");

export const metadata: Metadata = pageMetadata({
  path: "/privacy",
  title: route.metaTitle,
  description: route.description,
});

// WebPage + BreadcrumbList, built from the same registry entry as the metadata above. A legal
// page a crawler cannot type is a page it cannot place in the site; both of these are linked
// from every page's footer and both are in the sitemap.
const pageJsonLd = standalonePageJsonLd({
  slug: "privacy",
  navLabel: route.navLabel,
  metaTitle: route.metaTitle,
  description: route.description,
  dateModified: route.dateModified,
});



export default function PrivacyPage() {
  return (
    <PageShell>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(pageJsonLd).replace(/</g, "\\u003c") }}
      />
      <main id="main" className="mx-auto max-w-3xl px-5 py-14 sm:px-8 sm:py-20">
        <p className="mb-4 text-xs font-semibold uppercase tracking-[0.24em] text-accent">
          Legal
        </p>
        <h1 className="font-display text-4xl leading-tight text-ink sm:text-5xl">
          Privacy Policy
        </h1>
        <p className="mt-4 text-sm text-subtle">Last updated: {privacyLastUpdated}</p>

        <p className="mt-8 leading-7 text-subtle">
          This Privacy Policy explains how {brandName} (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or
          &ldquo;our&rdquo;) collects, uses, stores, and protects information when you visit this
          website or complete our fit check. We keep data collection to the minimum
          needed to respond to you and deliver our service.
        </p>

        <Section title="1. Information we collect">
          {/* The question list is GENERATED from lib/qualification.ts rather than typed
              out here. A hand-written enumeration was already out of date the moment the
              form changed, which on this page is not a cosmetic problem: it is a legal
              statement about what we hold. */}
          <p className="leading-7 text-subtle">
            <strong className="text-ink/90">Information you give us.</strong> When you complete
            the fit check, we collect the contact details you choose to provide &mdash; your name,
            work email and company, and your website if you add it &mdash; along with your service
            area, anything you add in the free-text notes, and your answers to these questions
            (the monthly fee is optional; the rest are needed to give you an honest answer):
          </p>
          <ul className="mt-3 space-y-2 leading-7 text-subtle">
            {ANSWER_KEYS.map((key) => (
              <BulletItem key={key}>{QUESTION_LABELS[key]}</BulletItem>
            ))}
          </ul>
          <p className="mt-4 leading-7 text-subtle">
            <strong className="text-ink/90">Information we derive.</strong> From those answers the
            site computes and stores a fit assessment &mdash; a result of &ldquo;strong fit&rdquo;,
            &ldquo;worth a conversation&rdquo; or &ldquo;not a fit&rdquo;, a numeric fit score, and
            a suggested starting plan. It is generated by a fixed set of rules, not by a person and
            not by a machine-learning model, it is shown to you on screen at the time, and it has
            no effect on you beyond deciding what we say next and whether we offer you a call. You
            can ask us for it, or to correct it, on the same basis as everything else below. Please
            share only what you&rsquo;re comfortable providing.
          </p>
          <p className="mt-4 leading-7 text-subtle">
            <strong className="text-ink/90">Information collected automatically.</strong> When you
            submit the form, our server records the date and time and the IP address the request
            came from, to prevent spam and abuse. Be aware that the IP address is stored alongside
            your submission for as long as we keep the submission, not just for the moment of the
            check. If you click &ldquo;Choose a time&rdquo; on the booking step, we also record that
            you reached that step, so we know which enquiries went on to book. We also record
            which page you completed the fit check on, and — if you arrived from one of our
            outreach emails via a tagged link — the short campaign tag in that link, so we can
            tell which message you came from. The tag identifies the message, not you.
          </p>
          {/* GENERATED from lib/attribution.ts, for the same reason the question list above is
              generated: a hand-written list of what we record is out of date the day the code
              changes, and on this page that is a false legal statement. */}
          <p className="mt-4 leading-7 text-subtle">
            <strong className="text-ink/90">Where your visit came from.</strong> So that we can
            tell which channels send us companies we can actually help, we record these values,
            when they exist:
          </p>
          <ul className="mt-3 space-y-2 leading-7 text-subtle">
            {ATTRIBUTION_KEYS.map((key) => (
              <BulletItem key={key}>{ATTRIBUTION_LABELS[key]}</BulletItem>
            ))}
          </ul>
          <p className="mt-4 leading-7 text-subtle">
            We record the path of that first page but never its query string, and the domain name
            of the referring site but never the full address you came from. Your browser keeps
            these values in its session storage — a first-party store that is not a cookie and is
            cleared when you close the tab — and sends them to our own server, and nowhere else,
            with each of the events listed below, starting with the one that records that your
            visit began, and with the fit check if you submit it. This site does <em>not</em> use
            third-party advertising, analytics, or cross-site tracking cookies, and it sets no
            cookies of its own.
          </p>
          {/* GENERATED from lib/events.ts. The site records a handful of first-party events so
              the owner can tell whether the pages and the form work; the published list is the
              code's own list, for the same reason the two lists above are generated. */}
          <p className="mt-4 leading-7 text-subtle">
            <strong className="text-ink/90">How the site is used.</strong> To tell whether this
            website and the fit check work, our own server records these first-party events:
          </p>
          <ul className="mt-3 space-y-2 leading-7 text-subtle">
            {EVENT_NAMES.map((name) => (
              <BulletItem key={name}>{EVENT_LABELS[name]}</BulletItem>
            ))}
          </ul>
          <p className="mt-4 leading-7 text-subtle">
            Each event carries the page it happened on and the visit-origin values listed above
            when they exist. The events your browser sends also carry a random value it makes up
            for the current tab, so that the steps of one visit can be read in order; the two our
            server records itself (the fit result and the scheduling link) carry no such value
            and no reference to your submission. That value is not a cookie; it is kept in
            your browser&rsquo;s session storage, is never tied to your name or email, is not used
            to recognise you on a later visit or on any other site, and is gone when you close the
            tab. No event contains your name, email, IP address or browser details — the only
            thing any event says about your device is, for the start of a visit, whether the
            screen was phone-sized — and none of this is sent to any advertising or analytics
            company. Requests from automated crawlers are discarded rather than recorded; our
            server tells them apart by the description every browser and crawler sends about
            itself, reads it for that decision only, and does not store it.
          </p>
        </Section>

        <Section title="2. How we use your information">
          <ul className="space-y-2 leading-7 text-subtle">
            <BulletItem>
              Respond to your enquiry, prepare your free pipeline audit, and schedule a walkthrough
              call if you want one.
            </BulletItem>
            <BulletItem>
              Assess fit and, if we work together, plan and deliver the agreed service.
            </BulletItem>
            <BulletItem>Maintain records of requests and protect against spam or misuse.</BulletItem>
            <BulletItem>Improve our website and the relevance of what we offer.</BulletItem>
          </ul>
          <p className="mt-4 leading-7 text-subtle">
            We do not sell your personal information, and we do not use it for unrelated
            advertising.
          </p>
        </Section>

        <Section title="3. Consent and legal basis">
          <p className="leading-7 text-subtle">
            The tick-box on the form is your consent to be <em>contacted</em> about your enquiry,
            and you can withdraw it at any time (see &ldquo;Your choices and rights&rdquo; below).
            Withdrawing it stops us contacting you; it does not by itself erase the record of your
            enquiry, which we keep on the basis of our legitimate interest in responding to
            business enquiries, running this website, and keeping records of who we have dealt
            with. You can ask us to delete that record too, and we will.
          </p>
        </Section>

        <Section title="3a. Information about prospects we research for clients">
          <p className="leading-7 text-subtle">
            Separately from this website, our service researches business contacts on behalf of our
            clients. That information comes from freely available public sources, is limited to
            business-context details, and always records the source it came from. If you have been
            contacted as a result of that work and want to be removed, tell us and we will add you
            to a suppression list immediately and permanently — you will not be contacted again for
            that client. This policy covers our own handling of that data; the client on whose
            behalf the outreach is sent is responsible for their own compliance obligations as the
            sender.
          </p>
          <p className="mt-4 leading-7 text-subtle">
            Where a business contact replies with interest and agrees to speak with the client, we
            keep the conversation and pass it, with a warm introduction, to the client it concerns.
            On our Opportunity Engine plan we also record what the contact tells us in that
            conversation — their role, the need they describe, the timing, details of the building
            or the work, and the next step they agreed to — and hand it to that client so its team
            can follow up. We record what a contact says; we do not invent details a contact
            did not give, and we never contact consumers.
          </p>
        </Section>

        <Section title="4. How we store and share it">
          <p className="leading-7 text-subtle">
            Form submissions are stored in our own records and in Google Workspace (Google Sheets).
            This website is hosted on Vercel, and scheduling is handled through Google Calendar.
            These providers process data on our behalf so we can run the service; we don&rsquo;t
            share your information with anyone else except where required by law. We limit access to
            your information to people who need it to respond to you or deliver the service.
          </p>
        </Section>

        <Section title="5. Data retention">
          <p className="leading-7 text-subtle">
            We keep request information for as long as needed to respond to you, deliver any agreed
            service, and meet legal or record-keeping obligations. When it&rsquo;s no longer needed,
            we delete it or remove identifying details. You can ask us to delete your information
            sooner at any time.
          </p>
        </Section>

        <Section title="6. Your choices and rights">
          <p className="leading-7 text-subtle">
            Depending on where you live, you may have the right to access, correct, delete, or
            restrict the use of your personal information, to object to certain processing, and to
            withdraw consent. To make a request, contact us using the details in section 9 below
            and tell us what you&rsquo;d like — we&rsquo;ll act on verified requests within a
            reasonable time and won&rsquo;t charge you for it. You can also ask us to stop
            contacting you and we will. We will not treat you differently for exercising any of
            these rights.
          </p>
        </Section>

        <Section title="7. Children's privacy">
          <p className="leading-7 text-subtle">
            This is a business-to-business service and is not directed to children. We do not
            knowingly collect personal information from anyone under 16.
          </p>
        </Section>

        <Section title="8. Changes to this policy">
          <p className="leading-7 text-subtle">
            We may update this policy from time to time. When we do, we&rsquo;ll revise the
            &ldquo;Last updated&rdquo; date above. Material changes will be reflected on this page.
          </p>
        </Section>

        <Section title="9. Who we are, and how to contact us">
          <p className="leading-7 text-subtle">
            {legalEntity ? (
              <>
                {brandName} is operated by {legalEntity}, which is responsible for the information
                described in this policy.
              </>
            ) : (
              <>
                {brandName} is the trading name of {legalEntityName}, a limited liability company
                formed in {entityFormationState}, which is responsible for the information described in
                this policy. Full registered business details are available on request.
              </>
            )}
          </p>
          <p className="mt-4 leading-7 text-subtle">
            For anything to do with this policy or your information — including access, correction,
            deletion, or asking us to stop contacting you —{" "}
            {contactEmail ? (
              <>
                email{" "}
                <a
                  href={`mailto:${contactEmail}?subject=Privacy%20request`}
                  className="text-accent underline-offset-4 hover:underline"
                >
                  {contactEmail}
                </a>
                . You do not need to fill in any form, and we will not ask you for more information
                than we need to find your record and verify the request.
              </>
            ) : (
              <>
                use the{" "}
                <Link href="/#contact" className="text-accent underline-offset-4 hover:underline">
                  request form
                </Link>{" "}
                and write &ldquo;Privacy&rdquo; in the notes. Only your name and email are needed to
                identify your record — you don&rsquo;t have to answer the questions about your
                business, and we will not use a privacy request as a reason to contact you about
                our services.
              </>
            )}
          </p>
        </Section>
      </main>
    </PageShell>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-10">
      <h2 className="font-display text-2xl text-ink">{title}</h2>
      <div className="mt-4">{children}</div>
    </section>
  );
}

function BulletItem({ children }: { children: React.ReactNode }) {
  return (
    <li className="flex gap-3">
      <span aria-hidden="true" className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-accent" />
      <span>{children}</span>
    </li>
  );
}
