import type { Metadata } from "next";
import Link from "next/link";
import GuideLayout, { GuideSection, KeyAnswer } from "@/components/GuideLayout";
import SpecimenDocument from "@/components/SpecimenDocument";
import { canonTerm, specimenList, termAnchor } from "@/lib/canon";
import { getGuidePage, guideJsonLd, pageMetadata } from "@/lib/pages";
import { brandName } from "@/lib/site";

// PROOF OF DELIVERY, WITHOUT INVENTING ANY.
//
// There is no client document to show yet, and inventing one — a client, a result, a quote, a
// number — is the one thing this business never does. So this page shows the work itself, in
// two honest forms, both generated by the operating system (lib/generated/specimens.ts):
//
//   * one REAL commercial account, researched from a dated public article and re-read on the
//     day it was published here, in the exact shape the send gate checks. The firm's name, the
//     link and the street addresses are withheld, as they are for every account we research;
//   * every other document RENDERED BY THE PRODUCTION CODE that renders a client's — the
//     handoff record, the opportunity brief, the client report — with a [bracketed placeholder]
//     wherever a real buyer's words or a real count would go. No number on this page is a
//     result.

const page = getGuidePage("sample-deliverables");

export const metadata: Metadata = pageMetadata({
  path: `/${page.slug}`,
  title: page.metaTitle,
  description: page.description,
});

const structuredData = guideJsonLd(page);

export default function SampleDeliverablesPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(structuredData).replace(/</g, "\\u003c"),
        }}
      />
      <GuideLayout
        page={page}
        eyebrow="Sample deliverables"
        intro={
          <>
            <p className="text-ink">
              These are the documents {brandName} hands a commercial HVAC contractor: the
              researched account, the qualification record, the warm handoff, the opportunity
              brief and the client report — each shown exactly as the system produces it.
            </p>
            <p>
              We have no case studies yet, so we show the work itself. The first document is a
              real account we researched from public sources. Every other document was produced by
              the same code that produces a client&rsquo;s, with a{" "}
              <span className="rounded bg-accent/10 px-1 font-medium text-accent">[bracketed placeholder]</span>{" "}
              wherever a real buyer&rsquo;s details or a real count would go. None of it is a
              client&rsquo;s document, and no number on this page is a result.
            </p>
            <p>
              Every term in them is defined once, on{" "}
              <Link href="/definitions" className="text-accent underline underline-offset-4">
                the definitions page
              </Link>
              .
            </p>
          </>
        }
      >
        {specimenList.map((s) => {
          const term = canonTerm(s.term);
          return (
            <GuideSection key={s.key} id={s.key} title={s.title}>
              <KeyAnswer>
                <p>
                  <span className="font-semibold">When: </span>
                  {s.when}
                </p>
                <p className="mt-2">
                  <span className="font-semibold">Plans: </span>
                  {s.plans.join(" and ")}
                </p>
                <p className="mt-2">
                  <span className="font-semibold">What this copy is: </span>
                  {s.provenance}
                </p>
              </KeyAnswer>
              <SpecimenDocument body={s.body} label={`Specimen — ${s.title}`} />
              <p className="text-sm">
                Defined:{" "}
                <Link href={`/definitions#${termAnchor(term.key)}`} className="text-accent underline underline-offset-4">
                  {term.label}
                </Link>
              </p>
            </GuideSection>
          );
        })}

        <GuideSection id="hub" title="The client performance hub">
          <p>
            Each client also receives a performance hub: the same counts as the report, the stage
            of every opportunity and the service timeline, in one file. It is delivered privately
            and never hosted at a public web address, so one client&rsquo;s prospects are never
            visible to anyone else.
          </p>
        </GuideSection>
      </GuideLayout>
    </>
  );
}
